### ISSUE TITLE
There is an error for reading commands

### ISSUE THREAD

**Issue by majeeddl** [fasterbase/cheetah#42]
![image](https://user-images.githubusercontent.com/472520/228461039-f2eb0b66-ac82-4551-bb6a-c2c6955c3fd2.png)

**Comment by farazfaraji** [comment]
@majeeddl I just tested this endpoint, seems it's working fine. can you explain more about it?

**Comment by majeeddl** [comment]
Sometimes endpoints do not work and errors are displayed. In addition, most
of the time, endpoints do not respond in a timely manner.
